SHELF = $(HOME)/development/git/coco-shelf
LWASM = $(SHELF)/bin/lwasm
NITROS9=$(HOME)/development/git/nitros9
OPTIONS=--pragma=pcaspcr,nosymbolcase,condundefzero,undefextern,dollarnotlocal,noforwardrefmax

all: protozip

protozip: protozip.asm
	$(LWASM) -f os9 $(OPTIONS) --includedir=$(NITROS9)/defs -o $@ $<
	imgtool create coco_jvc_os9 proto.dsk
	os9 format proto.dsk
	os9 copy protozip proto.dsk,protozip
	os9 attr -e -pe proto.dsk,protozip
	os9 copy sample.txt proto.dsk,sample.txt

clean:
	rm -f protozip proto.dsk *.list *.map *.bak
